pref("extensions.fessGBE.nestedLabelSep", "/");
pref("extensions.fessGBE.showFavicons", true);
pref("extensions.fessGBE.reverseBkmrkLeftClick", false);
pref("extensions.fessGBE.sortType", "name");
pref("extensions.fessGBE.sortOrder", "asc");
pref("extensions.fessGBE.suggestLabel", false);
pref("extensions.fessGBE.enableGBautocomplite", false);
pref("extensions.fessGBE.enableNotes", false);
pref("extensions.fessGBE.useMenuBar", false);